
ALTER TABLE EXERCISE
	ADD CONSTRAINT FK_RERSON
	FOREIGN KEY (FK_PERSON) 
	REFERENCES REGISTRY(PERSONID),
	aDD CONSTRAINT FK_SPORT
	FOREIGN KEY (FK_SPORT)
	REFERENCES SPORT(SPORTID);

ALTER TABLE ACTIVITY
	ADD CONSTRAINT FK_SPORT
	FOREIGN KEY (FK_SPORT)
	REFERENCES SPORT(SPORTID),
	ADD CONSTRAINT FK_REGISTRY
	FOREIGN KEY (FK_REGISTRY) 
	REFERENCES REGISTRY(REGISTRYID)	,
	ADD CONSTRAINT FK_TRAINING
	FOREIGN KEY (FK_TRAINING) 
	REFERENCES TRAINING(TRAININGID),
	ADD CONSTRAINT  FK_EXERCISE
	FOREIGN KEY (FK_EXERCISE) 
	REFERENCES EXERCISE(EXERCISEID);