CREATE TABLE SPORT (
	
	SPORTID			NUMERIC NOT NULL PRIMARY KEY,
	SPORTNAME			VARCHAR(50) NOT NULL,
	SPORTMET			NUMERIC

	);
CREATE SEQUENCE SPORTID;

CREATE TABLE EXERCISE(
	EXERCISEID			INTEGER NOT NULL PRIMARY KEY,
	FK_SPORT			INTEGER,
	FK_PERSON			INTEGER
);
CREATE SEQUENCE EXERCISEID;

CREATE TABLE ACTIVITY(

	ACTIVITYID			 INTEGER NOT NULL PRIMARY KEY,
	ACTIVITYSTARTTIME	 TIME,
	ACTIVITYENDTIME		 TIME,
	ACTIVITYDATE		 DATE,
	ACTIVITYKM			 NUMERIC NOT NULL,
	ACTIVITYCALOR		 NUMERIC,
	ACTIVITYSTARTSITE	 VARCHAR(200),
	ACTIVITYENDSITE		 VARCHAR(200),
	FK_REGISTRY	 		INTEGER,
	FK_TRAINING			INTEGER,
	FK_EXERCISE			INTEGER
);
CREATE SEQUENCE ACTIVITYID;

