


-- BUSCA EL ID DEL DEPORTE A TRAVES DE SU NOMBRE
-- FUE CREADO PARA OBTENER EL ID DEL DEPORTE ANTES DE INSERTAR

CREATE OR REPLACE FUNCTION obtenerDeporte (nombre VARCHAR(200)) RETURNS INTEGER AS 
$$ 
DECLARE
 resultado INTEGER;
BEGIN 

  SELECT SPORTID INTO  resultado
  FROM SPORT
  WHERE SPORTNAME=nombre;
  return(resultado);
  
END; 
$$
LANGUAGE 'plpgsql' STABLE;



-- INSERTA EL ID DEL USUARIO Y EL ID DEL DEPORTE 

CREATE OR REPLACE FUNCTION insertarDeporte(usuario INTEGER ,deporte INTEGER) RETURNS BOOLEAN AS $$
BEGIN
	 INSERT INTO EXERCISE (EXERCISEID,FK_PERSON,FK_SPORT) VALUES (nextval('EXERCISEID'),usuario,deporte);
	 
	 RETURN TRUE;
	 
END
$$
LANGUAGE 'plpgsql' VOLATILE; 

-- INSERTA LOS DATOS PARA EL REGISTROS DE LAS ACTIVIDADES

CREATE OR REPLACE FUNCTION insertarActividad (horainicio TIME, horafinal TIME, fecha DATE, km NUMERIC, caloria NUMERIC, lugarinicio VARCHAR(200),lugarfinal VARCHAR(200) ) RETURNS BOOLEAN AS $$
BEGIN
	 INSERT INTO  ACTIVITY (ACTIVITYID,ACTIVITYSTARTTIME, ACTIVITYENDTIME,ACTIVITYDATE,ACTIVITYKM ,ACTIVITYCALOR,ACTIVITYSTARTSITE,ACTIVITYENDSITE) VALUES (nextval('ACTIVITYID'),
                    horainicio,horafinal,fecha,km,caloria,lugarinicio,lugarfinal) ;
	 
	 RETURN TRUE;
	 
END
$$
LANGUAGE 'plpgsql' VOLATILE; 

--MODIFICAR ACTIVIDADES

CREATE OR REPLACE FUNCTION insertarActividad (horainicio TIME, horafinal TIME, fecha DATE, km NUMERIC, caloria NUMERIC, lugarinicio VARCHAR(200),lugarfinal VARCHAR(200) ) RETURNS BOOLEAN AS $$
BEGIN
	 INSERT INTO  ACTIVITY (ACTIVITYID,ACTIVITYSTARTTIME, ACTIVITYENDTIME,ACTIVITYDATE,ACTIVITYKM ,ACTIVITYCALOR,ACTIVITYSTARTSITE,ACTIVITYENDSITE) VALUES (nextval('ACTIVITYID'),
                    horainicio,horafinal,fecha,km,caloria,lugarinicio,lugarfinal) ;
	 
	 RETURN TRUE;
	 
END
$$
LANGUAGE 'plpgsql' VOLATILE; 

