	CREATE TABLE ACTIVITY(

	ACTIVITYID			 INTEGER NOT NULL PRIMARY KEY,
	ACTIVITYSTARTTIME	 TIME,
	ACTIVITYENDTIME		 TIME,
	ACTIVITYDATE		 DATE,
	ACTIVITYKM			 NUMERIC NOT NULL,
	ACTIVITYCALOR		 NUMERIC,
	ACTIVITYSTARTSITE	 VARCHAR(200),
	ACTIVITYENDSITE		 VARCHAR(200),
	FK_SPORT			INTEGER,
	FK_REGISTRY	 INTEGER,
	FK_TRAINING	INTEGER
);

INSERT INTO SPORT (SPORTID,SPORTNAME,SPORTMET) VALUES (nextval('SPORTID'),'CAMINAR',3.3);
INSERT INTO SPORT (SPORTID,SPORTNAME,SPORTMET) VALUES (nextval('SPORTID'),'TROTAR',7);
INSERT INTO SPORT (SPORTID,SPORTNAME,SPORTMET) VALUES (nextval('SPORTID'),'BICICLETA',8);
INSERT INTO SPORT (SPORTID,SPORTNAME,SPORTMET) VALUES (nextval('SPORTID'),'NATACION',8.5);
INSERT INTO SPORT (SPORTID,SPORTNAME,SPORTMET) VALUES (nextval('SPORTID'),'YOGA',2.5);
INSERT INTO SPORT (SPORTID,SPORTNAME,SPORTMET) VALUES (nextval('SPORTID'),'ESTIRAMIENTOS',2.5);
INSERT INTO SPORT (SPORTID,SPORTNAME,SPORTMET) VALUES (nextval('SPORTID'),'ELIPTICA',7);
INSERT INTO SPORT (SPORTID,SPORTNAME,SPORTMET) VALUES (nextval('SPORTID'),'ESCALERAS',9);
INSERT INTO SPORT (SPORTID,SPORTNAME,SPORTMET) VALUES (nextval('SPORTID'),'BAILAR',5);
INSERT INTO SPORT (SPORTID,SPORTNAME,SPORTMET) VALUES (nextval('SPORTID'),'AEROBIC',8.5);
INSERT INTO SPORT (SPORTID,SPORTNAME,SPORTMET) VALUES (nextval('SPORTID'),'REMO',8);
INSERT INTO SPORT (SPORTID,SPORTNAME,SPORTMET) VALUES (nextval('SPORTID'),'BASKETBALL',6);
INSERT INTO SPORT (SPORTID,SPORTNAME,SPORTMET) VALUES (nextval('SPORTID'),'FUTBOL',6.5);
INSERT INTO SPORT (SPORTID,SPORTNAME,SPORTMET) VALUES (nextval('SPORTID'),'TENIS',5);
INSERT INTO SPORT (SPORTID,SPORTNAME,SPORTMET) VALUES (nextval('SPORTID'),'VOLEIBOL',6.5);