
/*---------SECUENCIAS-------*/


CREATE SEQUENCE sportId;
CREATE SEQUENCE activityId;

/*---------DROPS-----------*/

DROP SEQUENCE sportId    CASCADE;
DROP SEQUENCE activityId CASCADE;

DROP TABLE SPORT		 CASCADE;
DROP TABLE ACTIVITY 	 CASCADE;